name: "Prune old artifacts"
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: kolpav/purge-artifacts-action@04c636a505f26ebc82f8d070b202fb87ff572b10 # v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days

